name: CI/CD Workshop
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
